name = "EXOSPHID"
uuid = "0712f75d-6a49-4df0-a6a3-d5e6ae96d6b8"
authors = ["Carlos GÃ³mez de Olea Ballester <carlos.olea@tum.de>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "1.8.1"
Distributions = "0.25.122"
Interpolations = "0.16.2"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
Test = "1.11.0"
julia = "1.11"
